-- local options = {
--   formatters_by_ft = {
--     lua = { "stylua" },
--     -- css = { "prettier" },
--       javascript = {"biome"},
--         html = { "prettier" },
--       },
--
--     format_on_save = {
--       timeout_ms = 500,
--       lsp_fallback = true,
--     },
--   }
--
-- r equire("conform").setup(options)
