return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "black",
      "debugpy",
      "mypy",
      "ruff",
      "pyright",
      "biome",
      "typescript-language-server",
      "lua-language-server",
      "sqlfmt",
      "sqlls",
      "prettier",
      "google-java-format",
      "eslint_d",
      "clangd",
      "clang-format",
      "codelldb",
      "gopls",
      "goimports",
    },
  },
}
